---
abstract: 'Test Project example of Dist::Zilla'
author:
  - agrangaard@rubiconproject.com
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.11
generated_by: 'Dist::Zilla version 1.100711'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: test-project
requires: {}
resources:
  repository: ~
version: 0.100840
